### ISSUE TITLE
Description of repository: Pointing to https://training.plone.org/5/voltohandson

### ISSUE THREAD

**Issue by ksuess** [collective/volto-hands-on-training#1]

**Comment by tkimnguyen** [comment]
@ksuess I don't understand the issue... it's a bit cryptic :)

**Comment by ksuess** [comment]
![image](https://user-images.githubusercontent.com/1144737/75222361-5c1ed900-57a4-11ea-9f5b-4949560d2122.png)
I just thougt a link https://training.plone.org/5/voltohandson to the training would be handy. 
Close this issue if you like.

**Comment by tkimnguyen** [comment]
I see the repo description has a link to that, and I've just made a PR so the README mentions the Volto Hands On training too https://github.com/collective/volto-hands-on-training/pull/4
